### ISSUE TITLE
Only accept links to .mp3s and known-good streaming services like SoundCloud

### ISSUE THREAD

**Issue by wilm0x42** [wilm0x42/wVote#10]
The main reason for this being that we use Groovy to play the entries in discord voice chat, and weird links like beepbox wouldn't work with that.

* Parse link to see if it's SoundCloud or Clyp or whatever, success if true
* (maybe) http HEAD the link to see if it's a valid audio file, success if true
* Otherwise, return an error message along the lines of: "Sorry, but we only accept links to .mp3 files, or to streaming services like SoundCloud. If you need help, DM a mod."

**Comment by Tordek** [comment]
Which hosts should be allowed? I'm starting checking on this.

**Comment by wilm0x42** [comment]
https://groovy.zendesk.com/hc/en-us/articles/360021234491-Supported-Platforms
So I'm thinking for starters:
* SoundCloud
* YouTube
* Clyp

That should be all that matters for now, until someone shows up saying "Why can't I submit my vimeo link?" :P

**Comment by wilm0x42** [comment]
Looks to me like #39 clears this up adequately
