### ISSUE TITLE
User manual wiki for admins

### ISSUE THREAD

**Issue by wilm0x42** [wilm0x42/wVote#11]
All the information relevant to handling the Admin side of things is a bit beyond what would fit into a block of text on the administration page.  It'd be handy to have everything written down in the github wiki, or at least a big ol' markdown file.

**Comment by MrMyastan** [comment]
https://github.com/wilm0x42/wVote/wiki/Admin-Guide I think clears this up?

**Comment by wilm0x42** [comment]
Yeah, we'll call that good enough for now.
