### ISSUE TITLE
Global configuration file

### ISSUE THREAD

**Issue by wilm0x42** [wilm0x42/wVote#14]
Currently, we don't actually have a global configuration file.  We have bot_config.conf for discord-specific stuff, but everything else is just stored in the next and current weeks.

We should probably make that a thing :P

**Comment by wilm0x42** [comment]
I imagine it'd probably be best to make this a .json file, so we can just trivially serialize a python object, but unlike pickle, we can easily textedit it for manual configuration.

**Comment by MrMyastan** [comment]
What should we put in this?

**Comment by wilm0x42** [comment]
tbh... I think we can just pass on this one
Like, if another miscellaneous configuration variable like debug mode shows up, we can probably just shoehorn it into bot.conf and it won't be a big deal.
For now, at least.
