### ISSUE TITLE
Voting web interface overhaul

### ISSUE THREAD

**Issue by wilm0x42** [wilm0x42/wVote#2]
We ultimately want it to be a smooth experience for people to listen and vote from their phones, so that the voting process can take place during their downtime.

**Comment by wilm0x42** [comment]
this is _probably_ gonna be done by way of a complete overhaul of the website ui

random note to influence designs: wiglaf asked to make it possible to resize the left/right panels of current design

**Comment by wilm0x42** [comment]
![proto_swi](https://user-images.githubusercontent.com/26749441/106321114-d91ec200-6241-11eb-9588-ea9bc9577e30.jpeg)
![protoa_azura](https://user-images.githubusercontent.com/26749441/106321118-dae88580-6241-11eb-9d1b-1478594906d6.png)
![proto_joshua](https://user-images.githubusercontent.com/26749441/106321121-dc19b280-6241-11eb-86f2-5c85da61411c.png)
![proto_wilm1](https://user-images.githubusercontent.com/26749441/106321133-e0de6680-6241-11eb-8ec4-2ba66c90c8ec.png)
![proto_wilm2](https://user-images.githubusercontent.com/26749441/106321150-e5a31a80-6241-11eb-97c7-13b9b86fc4d6.png)
a bunch of design concepts from the users

**Comment by wilm0x42** [comment]
![joshua2](https://user-images.githubusercontent.com/26749441/106344620-d7242580-6278-11eb-9972-2cac487c9247.png)

**Comment by wilm0x42** [comment]
![proto_aero](https://user-images.githubusercontent.com/26749441/106359406-a7a90380-62e0-11eb-80d9-405a37d69df2.png)
![proto_tek](https://user-images.githubusercontent.com/26749441/106359419-ae377b00-62e0-11eb-8094-e679f1af3efd.png)

**Comment by wilm0x42** [comment]
![mockup](https://user-images.githubusercontent.com/26749441/106372480-15cfe380-633e-11eb-978e-d57693af3082.png)
What we'll aim for

**Comment by wilm0x42** [comment]
Arbitrary list of remaining changes for THE  V U E N I N G
* Put voting categories in week data
* Make vote!myresults calculate gooder data
* Make vote!myresults have a little message about being chill about the data
* Make vote!myresults only available when voting is closed
* Give the admin interface controls to allow deletion of votes
* Weighted categories for STAR voting
* Abstract out some of the score-calculating code to be used in vote!myresults, so we're not repeating ourselves

**Comment by MrMyastan** [comment]
points 3 and 4 handled in #40

**Comment by wilm0x42** [comment]
Aaight, after we gives this some stress testing in beta test competitions, we'll merge to master and ask A exactly how he wants this introduced to the public.

**Comment by wilm0x42** [comment]
![normalization_explanation](https://user-images.githubusercontent.com/26749441/113521661-e7060180-9568-11eb-89d4-53f173212fa9.png)
putting this here so I can use the URL in the wiki, because *lmao image hosting*

**Comment by wilm0x42** [comment]
![normalization_explanation](https://user-images.githubusercontent.com/26749441/113521711-3f3d0380-9569-11eb-8ff1-7b1a2f983056.png)
image too big

**Comment by wilm0x42** [comment]
![normalization_explanation](https://user-images.githubusercontent.com/26749441/113662159-87494c80-9675-11eb-826a-00816f4840e6.png)
last minute update of this image
"lol," he said, "lmao"

**Comment by wilm0x42** [comment]
WOOOOOOOOOOO
