### ISSUE TITLE
Put the postentries code in a try: catch block

### ISSUE THREAD

**Issue by wilm0x42** [wilm0x42/wVote#24]
Crud can go wrong with just one entry, and that's not a big deal for the admins to handle.
But when it _does_ go wrong with an entry, we want things to continue so that the other entries after that one still get posted.

The only question here is finding what exceptions to catch, so TODO: collect a list of all the discord API exceptions that we want to catch

**Comment by MrMyastan** [comment]
As far as i can tell from looking through the API docs the only thing that raises anything is context.send() and we only have to worry about are Forbidden (don't have permission to send to channel) and HTTPException (failed to send)

**Comment by wilm0x42** [comment]
Related: we need to put compo.get_admin_form_for_entry in a try:catch block as well-- if that throws an error, the whole admin page breaks
