### ISSUE TITLE
Make preview window in admin page refresh when reloading week data

### ISSUE THREAD

**Issue by wilm0x42** [wilm0x42/wVote#65]
`document.getElementById('some_frame_id').contentWindow.location.reload();`
Someone's gotta find the right line of code to yeet this upon, and it sure ain't gonna be me right now

**Comment by Tordek** [comment]
It goes in admin.html after 299; also need to change line 90 to add the ID

**Comment by wilm0x42** [comment]
tordek gettin' them in #72 and #73
