### ISSUE TITLE
Alignment issue on voted successfully page

### ISSUE THREAD

**Issue by TrueAerosoul** [wilm0x42/wVote#80]
![image](https://user-images.githubusercontent.com/66096753/130344133-9b8f21a6-e073-49cd-82d1-a268b32b2dc3.png)

**Comment by wilm0x42** [comment]
the frick system are you viewing this crud on
(and what window size is this)

**Comment by wilm0x42** [comment]
a b642acf4c6746fae6784cb8aec5d3d1ea85b3901

**Comment by TrueAerosoul** [comment]
Unsure is this was ever resolved?
![image](https://user-images.githubusercontent.com/66096753/133725549-cb90cef0-4717-422d-a722-abeb2f9888bd.png)

**Comment by wilm0x42** [comment]
Ye, fixed in b642acf4c6746fae6784cb8aec5d3d1ea85b3901
I just haven't remembered to deploy that to the server
