### ISSUE TITLE
Mention in DMs that links expire

### ISSUE THREAD

**Issue by wilm0x42** [wilm0x42/wVote#9]

**Comment by wilm0x42** [comment]
And possibly have http server give "Link expired. Please ask for a new one in discord"

**Comment by above-c-level** [comment]
The first part of this should be pretty easy to implement. I've already refactored the default TTL out of functions in http_server as `default_ttl = 30` in the dev branch. Another `await message.channel.send()` in `on_message()` can pull from `http_server.default_ttl` to display the time, and if it ever changes should be sent out in message form as well.

**Comment by wilm0x42** [comment]
Gonna leave out the pretty http error-- That'd jank up the code too much. Maybe another time. ¯\\\_(ツ)\_/¯

**Comment by wilm0x42** [comment]
Done in 8a309ce35df12d963cca813c47bb428d0c9d2833
(Also, giving something other than 404 for expired/incorrect auth might not be excellent security-wise, so maybe we won't do that at all :P)
